baseURL = "http://example.com/"
languageCode = "en-us"
title = "TrungPQ"
theme = "diary"
googleAnalytics = ""

[params]
    author = "Pham Quang Trung"
    githubUsername = "#"
    accent = "pink"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "python", "php", "javascript", "typescript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/vnzinki"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/pqtr.f/"
    name = "fab fa-facebook"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/phamquangtrung/"
    name = "fab fa-linkedin"
    weight = 4
